
POST http://localhost:9000/api/entry
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"
//Content-Type: application/json

Fluff

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Sent from REST

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="Ninja10.jpg"
Content-Type: image/jpeg

< ./Ninja10.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

This is a default picture

------WebKitFormBoundary7MA4YWxkTrZu0gW--