#Get a list of all users if you are admin.
GET http://localhost:9000/api/user

###

#Get current logged in user if you have a cookie.
GET http://localhost:9000/api/user/login

###

#Create a new user, username has to be unique.
POST http://localhost:9000/api/user
Content-Type: application/json

{
    "username": "Rex",
    "password": "123456"
}

###

#Update user admin status true/false by id.
PUT http://localhost:9000/api/user/5ebd7fa85f2d4a307807eb6e
Content-Type: application/json

{
    "admin": "false"
}

###

#Delete user by id.
DELETE http://localhost:9000/api/user/5eb9371009094815bc038695

###

#Login - username/password.
POST http://localhost:9000/api/user/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

#Logout.
DELETE  http://localhost:9000/api/user/logout

###