
POST http://localhost:9000/api/user
Content-Type: application/json

{
    "username": "Lex",
    "password": "123456"
}

###

PUT http://localhost:9000/api/user
Content-Type: application/json

{
    "name": "Rex put",
    "mail": "def2@def2.com"
}

###

POST http://localhost:9000/api/user/login
Content-Type: application/json

{
    "username": "Lex",
    "password": "123456"
}

###

DELETE  http://localhost:9000/api/user/logout
Content-Type: application/json

{
}