GET http://localhost:9000/api/user

###

GET http://localhost:9000/api/user/login

###

POST http://localhost:9000/api/user
Content-Type: application/json

{
    "username": "Schampoo",
    "password": "123"
}

###

PUT http://localhost:9000/api/user/5eb9371009094815bc038695
Content-Type: application/json

{
    "username": "Rex put",
    "password": "password",
    "admin": "false"
}

###

DELETE http://localhost:9000/api/user/5eb9371009094815bc038695

###

POST http://localhost:9000/api/user/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

DELETE  http://localhost:9000/api/user/logout

###